apiVersion: v1
kind: Service
metadata:
  name: aa2-kubernetes
spec:
  type: LoadBalancer
  ports :
  - port: 80
    targetPort: 8080
  selector:
    app: aa2-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa2-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aa2-kubernetes
  template:
    metadata:
      labels:
        app: aa2-kubernetes
    spec:
      containers:
      - name: aa2-kubernetes
        image: icbmasterchief/bookybook-web-pro
        ports:
        - containerPort: 8080